twig:
    default_path: '%kernel.project_dir%/templates'


when@test:
    twig:
        strict_variables: true

#services:
#    App\Extensions\Twig\DateTwigExtension:
#        tags: ['twig.extension']
