vich_uploader:
    db_driver: orm
    
    metadata:
        type: attribute

    mappings:
        logo_file:
            uri_prefix: /uploads/logo/
            upload_destination: '%upload_directory_logo%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
